version: "3.8"

services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_DATABASE_USER
        - WORDPRESS_DATABASE_USER_PASSWORD
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    expose:
      - "443"
    volumes:
      - wordpress:/var/www

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tduprez/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tduprez/data/mariadb

#    external: true

networks:
  inception:
    name: inception
    driver: bridge

