version: "3.8"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
  wordpress:
    volumes:
      - type: volume
        source: wordpressVolume
        target: /var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    expose:
      - "443"
    volumes:
      - type: volume
        source: wordpressVolume
        target: /var/www/wordpress

volumes:
  wordpressVolume:
#    external: true

networks:
  inception:
    name: inception
    driver: bridge

